import type { Metadata } from 'next';
import Link from 'next/link';
import ServiceCard from '../../components/ServiceCard';
import services from '../../src/content/services.json';
export const metadata: Metadata = { title: 'Our Treatments' };
export default function ServicesPage() { return <><PageHero tibetan="སྨན་གྱི་གཞུང་འཇལ།" title="Our Treatments" subtitle="Individualised Tibetan Medicine & Ayurvedic therapies — each uniquely tailored to your constitution and health goals." /><section className="section"><div className="container"><div className="grid-3">{services.map((service) => <ServiceCard key={service.id} {...service} />)}</div></div></section><section className="section surface-white"><div className="container info-grid"><Info icon="⏱️" title="Session Duration">Initial consultations are typically 60–90 minutes, allowing Emchi to conduct a thorough pulse assessment and establish your personalized treatment plan. Follow-up sessions are 30–60 minutes.</Info><Info icon="🏥" title="What to Expect">You&apos;ll be warmly welcomed and asked about your health history, diet, lifestyle, and concerns. Emchi will then perform a traditional pulse reading before recommending treatment.</Info><Info icon="📅" title="Booking & Location">Consultations are available in Werribee, VIC, and monthly at Tara Institute. All treatments are by appointment.</Info></div></section><section className="cta-banner"><div className="container cta-inner"><h2>Ready to Begin?</h2><p>Contact Emchi Tsundu Dolma to discuss which treatment is right for you.</p><div className="cta-actions"><Link href="/contact" className="btn btn-secondary">Book a Consultation</Link><a href="tel:+61458494785" className="btn btn-outline">Call Now</a></div></div></section></> }
function PageHero({ tibetan, title, subtitle }: { tibetan: string; title: string; subtitle: string }) { return <section className="page-hero"><div className="container"><p className="page-hero-tibetan tibetan-script">{tibetan}</p><h1>{title}</h1><p>{subtitle}</p></div><div className="page-hero-wave"><svg viewBox="0 0 1440 60" preserveAspectRatio="none" aria-hidden="true"><path d="M0,30 C360,60 1080,0 1440,30 L1440,60 L0,60 Z" fill="#F5F1E8" /></svg></div></section> }
function Info({ icon, title, children }: { icon: string; title: string; children: React.ReactNode }) { return <article className="info-card"><span>{icon}</span><h2>{title}</h2><p>{children}</p></article> }
export { PageHero };
