import type { Metadata } from 'next';
import Link from 'next/link';
import ServiceCard from '../components/ServiceCard';
import ConditionCard from '../components/ConditionCard';
import services from '../src/content/services.json';
import conditions from '../src/content/conditions.json';

export const metadata: Metadata = { title: 'Home', description: 'Emchi Tsundu Dolma — Tibetan Medicine & Ayurveda practitioner in Werribee, VIC.' };

export default function HomePage() {
  return <><section className="hero" aria-labelledby="hero-heading"><div className="hero-blob hero-blob--1" /><div className="hero-blob hero-blob--2" /><div className="corner-pattern corner-tl"><img src="/images/patterns/tibetan-border.svg" alt="" width="120" height="120" /></div><div className="corner-pattern corner-tr"><img src="/images/patterns/tibetan-border.svg" alt="" width="120" height="120" /></div><div className="container hero-inner"><div className="hero-image-wrap"><div className="pulse-ring pulse-ring--1" /><div className="pulse-ring pulse-ring--2" /><img src="/images/medicine-buddha.png" alt="Medicine Buddha — Sangye Menla" className="hero-buddha" width="320" height="320" /></div><div className="hero-content"><p className="hero-tibetan tibetan-script">གསོ་བ་རིག་པས།</p><h1 id="hero-heading" className="hero-title">Emchi Dolma</h1><p className="hero-tagline">Tibetan Sorig · Ayurveda · Wellness</p><div className="hero-divider" aria-hidden="true"><span /><span>ཨོཾ་</span><span /></div><blockquote className="hero-quote"><p>“As long as beings are sick, until their illness is cured, may I become the medicine, the physician, and the one who nurses and cares for them.”</p><footer>— Medicine Buddha Prayer</footer></blockquote><p className="hero-practitioner"><strong>Emchi Tsundu Dolma</strong> — Tibetan Medicine & Ayurveda Consultant<br /><span>Werribee, VIC · By appointment · 0458 494 785</span></p><div className="hero-actions"><Link href="/contact" className="btn btn-secondary">Book a Consultation</Link><Link href="/services" className="btn btn-outline">Our Services</Link></div></div></div></section>
    <section className="about-strip"><div className="container about-strip-inner"><span className="about-strip-icon">🌿</span><div><h2>Emchi Tsundu Dolma</h2><p>Graduate of <strong>Men-Tsee-Khang</strong>, Dharamshala, India — the principal institution of Tibetan Medicine. With over <strong>10 years</strong> of experience combining Sowa Rigpa and Ayurveda, Emchi brings authentic ancient healing to Werribee and Melbourne.</p></div><Link href="/about" className="btn btn-primary">Learn More About Emchi →</Link></div></section>
    <section className="section"><div className="container"><h2 className="section-title">Our Treatments</h2><div className="section-divider"><span /><span /></div><p className="section-subtitle">Comprehensive Sowa Rigpa treatments rooted in 2,500 years of Tibetan healing wisdom, personalised to your unique constitution.</p><div className="grid-3">{services.map((service) => <ServiceCard key={service.id} {...service} />)}</div><p className="section-cta"><Link href="/services" className="btn btn-primary">View All Treatments →</Link></p></div></section>
    <section className="section surface-white"><div className="container conditions-inner"><div className="conditions-header"><h2 className="section-title section-title-left">What Can Tibetan Medicine Help With?</h2><div className="section-divider section-divider-left"><span /><span /></div><p className="section-subtitle section-subtitle-left">Sowa Rigpa addresses root causes — not just symptoms. These are some of the conditions that respond beautifully to traditional Tibetan healing.</p><Link href="/contact" className="btn btn-secondary">Book a Consultation</Link></div><div className="conditions-grid">{conditions.map((condition) => <ConditionCard key={condition.id} {...condition} />)}</div></div></section>
    <section className="cta-banner"><div className="container cta-inner"><p className="cta-tibetan tibetan-script">ལུས་སེམས་གཉིས་ཀ་གཞན་བཟང་འགྱུར།</p><h2>Begin Your Healing Journey Today</h2><p>Every healing journey begins with a single step. Book your initial consultation and discover what Tibetan Medicine can do for you.</p><div className="cta-actions"><Link href="/contact" className="btn btn-secondary">Book a Consultation</Link><a href="tel:+61458494785" className="btn btn-outline">Call 0458 494 785</a></div></div></section></>;
}
